-- MySQL Script generated by MySQL Workbench
-- Sat Aug 31 16:30:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema train_booking_system
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `train_booking_system` ;

-- -----------------------------------------------------
-- Schema train_booking_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `train_booking_system` DEFAULT CHARACTER SET utf8mb4 ;
USE `train_booking_system` ;

-- -----------------------------------------------------
-- Table `train_booking_system`.`train_station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_booking_system`.`train_station` ;

CREATE TABLE IF NOT EXISTS `train_booking_system`.`train_station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `station_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_booking_system`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_booking_system`.`schedule` ;

CREATE TABLE IF NOT EXISTS `train_booking_system`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_booking_system`.`train_journey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_booking_system`.`train_journey` ;

CREATE TABLE IF NOT EXISTS `train_booking_system`.`train_journey` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `schedule_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_schedule_id_idx` (`schedule_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_id`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `train_booking_system`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_booking_system`.`journey_station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_booking_system`.`journey_station` ;

CREATE TABLE IF NOT EXISTS `train_booking_system`.`journey_station` (
  `journey_id` INT NOT NULL,
  `station_id` INT NOT NULL,
  `stop_order` VARCHAR(45) NOT NULL,
  `departure_time` DATETIME NOT NULL,
  INDEX `fk_journey_id_idx` (`journey_id` ASC) VISIBLE,
  INDEX `fk_station_id_idx` (`station_id` ASC) VISIBLE,
  CONSTRAINT `fk_journey_id`
    FOREIGN KEY (`journey_id`)
    REFERENCES `train_booking_system`.`train_journey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_station_id`
    FOREIGN KEY (`station_id`)
    REFERENCES `train_booking_system`.`train_station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_booking_system`.`carriage_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_booking_system`.`carriage_class` ;

CREATE TABLE IF NOT EXISTS `train_booking_system`.`carriage_class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class_name` VARCHAR(45) NOT NULL,
  `seating_capacity` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_booking_system`.`journey_carriage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_booking_system`.`journey_carriage` ;

CREATE TABLE IF NOT EXISTS `train_booking_system`.`journey_carriage` (
  `journey_id` INT NOT NULL,
  `carriage_class_id` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  INDEX `fk_journey_id_idx` (`journey_id` ASC) VISIBLE,
  INDEX `fk_carriage_class_id_idx` (`carriage_class_id` ASC) VISIBLE,
  CONSTRAINT `fk_journey_id`
    FOREIGN KEY (`journey_id`)
    REFERENCES `train_booking_system`.`train_journey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carriage_class_id`
    FOREIGN KEY (`carriage_class_id`)
    REFERENCES `train_booking_system`.`carriage_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_booking_system`.`carriage_price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_booking_system`.`carriage_price` ;

CREATE TABLE IF NOT EXISTS `train_booking_system`.`carriage_price` (
  `schedule_id` INT NOT NULL,
  `carriage_class_id` INT NOT NULL,
  `price` FLOAT NOT NULL,
  INDEX `fk_schedule_id_idx` (`schedule_id` ASC) VISIBLE,
  INDEX `fk_carriage_class_id_idx` (`carriage_class_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_id`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `train_booking_system`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carriage_class_id`
    FOREIGN KEY (`carriage_class_id`)
    REFERENCES `train_booking_system`.`carriage_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_booking_system`.`passenger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_booking_system`.`passenger` ;

CREATE TABLE IF NOT EXISTS `train_booking_system`.`passenger` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_booking_system`.`booking_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_booking_system`.`booking_status` ;

CREATE TABLE IF NOT EXISTS `train_booking_system`.`booking_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_booking_system`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_booking_system`.`booking` ;

CREATE TABLE IF NOT EXISTS `train_booking_system`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `booking_date` DATE NOT NULL,
  `train_journey_id` INT NOT NULL,
  `starting_station_id` INT NOT NULL,
  `ending_station_id` INT NOT NULL,
  `ticket_class_id` INT NOT NULL,
  `amount_paid` FLOAT NOT NULL,
  `ticket_no` VARCHAR(45) NOT NULL,
  `seat_no` VARCHAR(45) NOT NULL,
  `passenger_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_train_journey_id_idx` (`train_journey_id` ASC) VISIBLE,
  INDEX `fk_starting_station_id_idx` (`starting_station_id` ASC) VISIBLE,
  INDEX `fk_ending_station_id_idx` (`ending_station_id` ASC) VISIBLE,
  INDEX `fk_ticket_class_id_idx` (`ticket_class_id` ASC) VISIBLE,
  INDEX `fk_passenger_id_idx` (`passenger_id` ASC) VISIBLE,
  INDEX `fk_status_id_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `fk_train_journey_id`
    FOREIGN KEY (`train_journey_id`)
    REFERENCES `train_booking_system`.`train_journey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_starting_station_id`
    FOREIGN KEY (`starting_station_id`)
    REFERENCES `train_booking_system`.`train_station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ending_station_id`
    FOREIGN KEY (`ending_station_id`)
    REFERENCES `train_booking_system`.`train_station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_class_id`
    FOREIGN KEY (`ticket_class_id`)
    REFERENCES `train_booking_system`.`carriage_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passenger_id`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `train_booking_system`.`passenger` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_status_id`
    FOREIGN KEY (`status_id`)
    REFERENCES `train_booking_system`.`booking_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
