-- MySQL Script generated by MySQL Workbench
-- Sat Aug 31 12:34:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema food_delivery_app
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `food_delivery_app` ;

-- -----------------------------------------------------
-- Schema food_delivery_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_delivery_app` DEFAULT CHARACTER SET utf8mb4 ;
USE `food_delivery_app` ;

-- -----------------------------------------------------
-- Table `food_delivery_app`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery_app`.`customer` ;

CREATE TABLE IF NOT EXISTS `food_delivery_app`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`delivery_driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery_app`.`delivery_driver` ;

CREATE TABLE IF NOT EXISTS `food_delivery_app`.`delivery_driver` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery_app`.`country` ;

CREATE TABLE IF NOT EXISTS `food_delivery_app`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery_app`.`address` ;

CREATE TABLE IF NOT EXISTS `food_delivery_app`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unit_number` VARCHAR(10) NULL,
  `street_number` VARCHAR(10) NULL,
  `address_line1` VARCHAR(100) NOT NULL,
  `address_line2` VARCHAR(100) NULL,
  `city` VARCHAR(15) NULL,
  `region` VARCHAR(25) NULL,
  `postal_code` VARCHAR(25) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_country_id_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `food_delivery_app`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery_app`.`restaurant` ;

CREATE TABLE IF NOT EXISTS `food_delivery_app`.`restaurant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(45) NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_address_id_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `food_delivery_app`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`menu_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery_app`.`menu_item` ;

CREATE TABLE IF NOT EXISTS `food_delivery_app`.`menu_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT NOT NULL,
  `item_name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_restaurant_id_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `food_delivery_app`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`customer_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery_app`.`customer_address` ;

CREATE TABLE IF NOT EXISTS `food_delivery_app`.`customer_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_address_id_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `food_delivery_app`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `food_delivery_app`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`order_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery_app`.`order_status` ;

CREATE TABLE IF NOT EXISTS `food_delivery_app`.`order_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status_value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`food_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery_app`.`food_order` ;

CREATE TABLE IF NOT EXISTS `food_delivery_app`.`food_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `restaurant_id` INT NOT NULL,
  `order_status_id` INT NOT NULL,
  `assigned_driver_id` INT NOT NULL,
  `order_datetime` DATETIME NOT NULL,
  `delivery_fee` FLOAT NULL,
  `total_amount` DECIMAL NOT NULL,
  `requested_delivery_datetime` DATETIME NULL,
  `cust_driver_rating` TINYINT NULL,
  `cust_restaurant_rating` TINYINT NULL,
  `customer_address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_restaurant_id_idx` (`restaurant_id` ASC) VISIBLE,
  INDEX `fk_customer_address_id_idx` (`customer_address_id` ASC) VISIBLE,
  INDEX `fk_order_status_id_idx` (`order_status_id` ASC) VISIBLE,
  INDEX `fk_driver_id_idx` (`assigned_driver_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `food_delivery_app`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `food_delivery_app`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_address_id`
    FOREIGN KEY (`customer_address_id`)
    REFERENCES `food_delivery_app`.`customer_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_status_id`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `food_delivery_app`.`order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_driver_id`
    FOREIGN KEY (`assigned_driver_id`)
    REFERENCES `food_delivery_app`.`delivery_driver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery_app`.`order_menu_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery_app`.`order_menu_item` ;

CREATE TABLE IF NOT EXISTS `food_delivery_app`.`order_menu_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `menu_item_id` INT NOT NULL,
  `qty_ordered` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_menu_item_id_idx` (`menu_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `food_delivery_app`.`food_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_item_id`
    FOREIGN KEY (`menu_item_id`)
    REFERENCES `food_delivery_app`.`menu_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
