-- MySQL Script generated by MySQL Workbench
-- Sat Aug 31 17:25:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel` ;

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8mb4 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`floor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`floor` ;

CREATE TABLE IF NOT EXISTS `hotel`.`floor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `floor_number` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`room_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`room_class` ;

CREATE TABLE IF NOT EXISTS `hotel`.`room_class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class_name` VARCHAR(45) NOT NULL,
  `base_price` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`room_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`room_status` ;

CREATE TABLE IF NOT EXISTS `hotel`.`room_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`room` ;

CREATE TABLE IF NOT EXISTS `hotel`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `floor_id` INT NOT NULL,
  `room_number` INT NOT NULL,
  `room_class_id` INT NOT NULL,
  `room_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_floor_id_idx` (`floor_id` ASC) VISIBLE,
  INDEX `fk_room_class_id_idx` (`room_class_id` ASC) VISIBLE,
  INDEX `fk_room_status_id_idx` (`room_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_floor_id`
    FOREIGN KEY (`floor_id`)
    REFERENCES `hotel`.`floor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_class_id`
    FOREIGN KEY (`room_class_id`)
    REFERENCES `hotel`.`room_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_status_id`
    FOREIGN KEY (`room_status_id`)
    REFERENCES `hotel`.`room_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`guest` ;

CREATE TABLE IF NOT EXISTS `hotel`.`guest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`payment_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`payment_status` ;

CREATE TABLE IF NOT EXISTS `hotel`.`payment_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`booking` ;

CREATE TABLE IF NOT EXISTS `hotel`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `guest_id` INT NOT NULL,
  `check_in_date` DATETIME NOT NULL,
  `check_out_date` DATETIME NOT NULL,
  `num_of_adults` TINYINT NOT NULL,
  `num_children` TINYINT NOT NULL,
  `room_id` INT NOT NULL,
  `booking_amount` FLOAT NOT NULL,
  `payment_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_guest_id_idx` (`guest_id` ASC) VISIBLE,
  INDEX `fk_payment_status_id_idx` (`payment_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_guest_id`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel`.`guest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_status_id`
    FOREIGN KEY (`payment_status_id`)
    REFERENCES `hotel`.`payment_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`booking_room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`booking_room` ;

CREATE TABLE IF NOT EXISTS `hotel`.`booking_room` (
  `booking_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  INDEX `fk_booking_id_idx` (`booking_id` ASC) VISIBLE,
  INDEX `fk_room_id_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_booking_id`
    FOREIGN KEY (`booking_id`)
    REFERENCES `hotel`.`booking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `hotel`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`feature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`feature` ;

CREATE TABLE IF NOT EXISTS `hotel`.`feature` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `feature_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`room_class_feature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`room_class_feature` ;

CREATE TABLE IF NOT EXISTS `hotel`.`room_class_feature` (
  `room_class_id` INT NOT NULL,
  `feature_id` INT NOT NULL,
  INDEX `fk_room_class_id_idx` (`room_class_id` ASC) VISIBLE,
  INDEX `fk_feature_id_idx` (`feature_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_class_id`
    FOREIGN KEY (`room_class_id`)
    REFERENCES `hotel`.`room_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feature_id`
    FOREIGN KEY (`feature_id`)
    REFERENCES `hotel`.`feature` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`bed_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`bed_type` ;

CREATE TABLE IF NOT EXISTS `hotel`.`bed_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bed_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`room_class_bed_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`room_class_bed_type` ;

CREATE TABLE IF NOT EXISTS `hotel`.`room_class_bed_type` (
  `room_class_id` INT NOT NULL,
  `bed_type_id` INT NOT NULL,
  `num_of_beds` TINYINT NOT NULL,
  INDEX `fk_room_class_id_idx` (`room_class_id` ASC) VISIBLE,
  INDEX `fk_bed_type_id_idx` (`bed_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_class_id`
    FOREIGN KEY (`room_class_id`)
    REFERENCES `hotel`.`room_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bed_type_id`
    FOREIGN KEY (`bed_type_id`)
    REFERENCES `hotel`.`bed_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`addon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`addon` ;

CREATE TABLE IF NOT EXISTS `hotel`.`addon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `addon_name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`booking_addon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`booking_addon` ;

CREATE TABLE IF NOT EXISTS `hotel`.`booking_addon` (
  `addon_id` INT NOT NULL,
  `booking_id` INT NOT NULL,
  INDEX `fk_addon_id_idx` (`addon_id` ASC) VISIBLE,
  INDEX `fk_booking_id_idx` (`booking_id` ASC) VISIBLE,
  CONSTRAINT `fk_addon_id`
    FOREIGN KEY (`addon_id`)
    REFERENCES `hotel`.`addon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_id`
    FOREIGN KEY (`booking_id`)
    REFERENCES `hotel`.`booking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
